spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pepe
    username: pepe
    password: pepedev
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never
